--- 
files: 
  - 
    destination: /var/www/html/
    source: content/
hooks: 
  AfterInstall: 
    - 
      location: scripts/changeperms.sh
      timeout: 180
    - 
      location: scripts/copysettings.sh
      timeout: 120
    - 
      location: scripts/install_new_relic.sh
      runas: root
      timeout: 180
  ApplicationStart: 
    - 
      location: scripts/start_httpd.sh
      timeout: 120
    - 
      location: scripts/register_with_elb.sh
      timeout: 120
  ApplicationStop: 
    - 
      location: scripts/deregister_from_elb.sh
      timeout: 120
    - 
      location: scripts/stop_httpd.sh
      timeout: 120
  BeforeInstall: 
    - 
      location: scripts/rmoldsite.sh
      timeout: 120
  ValidateService: 
    - 
      location: scripts/validate.sh
os: linux
version: 0.0
